name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # https://go.dev/doc/faq#git_https
    # https://github.com/actions/checkout/tree/v2.0.0#checkout-a-different-private-repository
    - name: Set up .netrc
      run: echo 'machine github.com login andrewmcwatters password ${{ secrets.GH_PAT }}' > $HOME/.netrc

    # https://go.dev/doc/faq#git_https
    - name: Set up Git
      run: /usr/bin/git config --global url.ssh://git@github.com/.insteadOf https://github.com/

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
